services:
  grafana:
    image: grafana/grafana:12.0.1
    ports:
      - "3000:3000"
    volumes:
      - ./etc/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./etc/grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./etc/grafana/dashboards:/etc/grafana/dashboards
      - ./etc/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafanazerotohero-demoapp-app/dist/:/var/lib/grafana/plugins/demoapp-app
    environment:
      - GF_INSTALL_PLUGINS=redis-app,grafana-resourcesexporter-app

  redis:
    image: redis:7.4
    ports:
      - "6379:6379"
    volumes:
      - ./etc/dump.rdb:/data/dump.rdb

  app-plugin:
    image: node:22
    volumes:
      - ./grafanazerotohero-demoapp-app:/app
    command: ["sh", "-c", "cd /app && npm install && npm run build"]
