{
 "title": "Business Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "KPI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Revenue (last 1h)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum (\n  sum_over_time(\n    {container=\"payment\"} |= \"Transaction complete.\" |= \"USD\"\n    | json\n    | unwrap amount_units_low [1h]\n  )\n)"
    }
   ]
  },
  {
   "title": "Average Order Value",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum (\n  sum_over_time(\n    {container=\"payment\"} |= \"Transaction complete.\" |= \"USD\"\n    | json\n    | unwrap amount_units_low [5m]\n  )\n)\n/ \nsum(\n  count_over_time(\n    {container=\"payment\"} |= \"Transaction complete.\" |= \"USD\" [5m]\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Order Rate (5m avg)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(app_payment_transactions_total{app_payment_currency=\"USD\"}[5m])*300",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Checkout Success Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(app_frontend_requests_total{target=\"/api/checkout\", method=\"POST\", status=\"200\"}[5m]))\n/\nsum(rate(app_frontend_requests_total{target=\"/api/checkout\", method=\"POST\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Checkout p95 Latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \n  sum(rate(rpc_server_duration_milliseconds_bucket{service_name=\"checkout\", rpc_method=\"PlaceOrder\"}[5m])) by (le)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Recommendation p95 Latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n    service_name=\"recommendation\",\n    span_kind=\"SPAN_KIND_SERVER\"\n  }[5m])) by (le)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Home Page Views",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "/min" } },
   "targets": [
    {
     "expr": "sum(rate(traces_span_metrics_calls_total{service_name=\"frontend\", span_name=\"GET /\"}[5m]))*60",
     "legendFormat": "Home Page Views"
    }
   ]
  },
  {
   "title": "Orders Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "/min" } },
   "targets": [
    {
     "expr": "rate(app_payment_transactions_total{app_payment_currency=\"USD\"}[5m])*60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Order Value Trend",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum (\n  sum_over_time(\n    {container=\"payment\"} |= \"Transaction complete.\" |= \"USD\"\n    | json\n    | unwrap amount_units_low [5m]\n  )\n)\n/ \nsum(\n  count_over_time(\n    {container=\"payment\"} |= \"Transaction complete.\" |= \"USD\" [5m]\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Service Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "/min" } },
   "targets": [
    {
     "expr": "sum(rate(traces_span_metrics_calls_total{status_code=\"STATUS_CODE_ERROR\"}[5m])) by (service_name)*60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Marketing Campaigns",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "parser": "backend",
     "source": "url",
     "type": "csv",
     "url": "http://localhost:3000/public/csv/campaign.csv",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  { "title": "Technical Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "container_cpu_utilization_ratio{}",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_total_bytes{}",
     "legendFormat": "{{container_name}}"
    }
   ]
  }
 ]
}