# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Prometheus
    orgId: 1

# list of datasources to insert/update depending
# what's available in the database
datasources:
  # <string, required> name of the datasource. Required
  - uid: "redis"
    orgId: "1"
    name: "redis-datasource"
    type: "redis-datasource"
    typeName: "Redis"
    access: "proxy"
    url: "redis://redis:6379"
    user: ""
    database: ""
    basicAuth: false
    isDefault: false
    jsonData: 
      acl: false
      client: "standalone"
      tlsAuth: false
    readOnly: false
  - name: gdev-testdata
    type: testdata
