# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Prometheus
    orgId: 1

# list of datasources to insert/update depending
# what's available in the database
datasources:
  # <string, required> name of the datasource. Required
  - uid: "infinity-api"
    orgId: 1
    name: "api"
    type: "yesoreyeram-infinity-datasource"
    typeName: "Infinity"
    access: "proxy"
    url: "http://app:8000"
    user: ""
    database: ""
    basicAuth: false
    isDefault: false
    jsonData: 
      customHealthCheckEnabled: true
      global_queries: 
    readOnly: false
  - uid: "infinity-general"
    orgId: 1
    name: "general"
    type: "yesoreyeram-infinity-datasource"
    typeName: "Infinity"
    access: "proxy"
    url: ""
    user: ""
    database: ""
    basicAuth: false
    isDefault: false
    jsonData: 
      global_queries: 
    readOnly: false

