{
 "title": "Service Performance Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(traces_span_metrics_calls_total,service_name)"
    }
   },
   {
    "name": "span_kind",
    "label": "Span Kind",
    "query": {
     "query": "label_values(traces_span_metrics_calls_total{service_name=\"$service\"},span_kind)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_span_metrics_duration_milliseconds_bucket{service_name=\"$service\", span_kind=\"$span_kind\"}[3m])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(traces_span_metrics_duration_milliseconds_bucket{service_name=\"$service\", span_kind=\"$span_kind\"}[3m])) by (le))",
     "legendFormat": "75th"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(traces_span_metrics_duration_milliseconds_bucket{service_name=\"$service\", span_kind=\"$span_kind\"}[3m])) by (le))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(service_name, span_kind) (traces_span_metrics_calls_total{service_name=\"$service\", span_kind=\"$span_kind\",status_code=\"STATUS_CODE_ERROR\"}) / sum by(service_name, span_kind) (traces_span_metrics_calls_total{service_name=\"$service\", span_kind=\"$span_kind\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(service_name, span_kind) (rate(traces_span_metrics_calls_total{service_name=\"$service\", span_kind=\"$span_kind\"}[3m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operations metrics under $service",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_span_metrics_duration_milliseconds_bucket{service_name=\"$service\", span_kind=\"$span_kind\"}[3m])) by (le, span_name))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(service_name, span_kind, span_name) (traces_span_metrics_calls_total{service_name=\"$service\", span_kind=\"$span_kind\",status_code=\"STATUS_CODE_ERROR\"}) / sum by(service_name, span_kind, span_name) (traces_span_metrics_calls_total{service_name=\"$service\", span_kind=\"$span_kind\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(service_name, span_kind, span_name) (rate(traces_span_metrics_calls_total{service_name=\"$service\", span_kind=\"$span_kind\"}[3m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_span_metrics_duration_milliseconds_bucket{service_name=\"$service\", span_kind=\"$span_kind\"}[3m])) by (le, service_name, span_kind, span_name)) * sum by(service_name, span_kind, span_name) (rate(traces_span_metrics_calls_total{service_name=\"$service\", span_kind=\"$span_kind\"}[3m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}