services:
  loki:
    image: grafana/loki:3.5.0
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  grafana:
    image: grafana/grafana:12.0.1
    ports:
      - "3000:3000"
    volumes:
      - ./etc/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./etc/grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./etc/grafana/dashboards:/etc/grafana/dashboards
      - ./etc/grafana/alerting:/etc/grafana/provisioning/alerting
      - ./etc/grafana/grafana.ini:/etc/grafana/grafana.ini
      - grafana-data:/var/lib/grafana
    environment:
      GF_FEATURE_TOGGLES_ENABLE: alertingCentralAlertHistory,sqlExpressions
    depends_on:
      - loki

  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - "8081:8081"

  prometheus:
    image: prom/prometheus:v3.4.1
    ports:
      - "9090:9090"
    volumes:
      - ./etc/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - node-exporter
      - cadvisor

  node-exporter:
    image: prom/node-exporter:v1.9.1
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.52.0
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

  nginx:
    image: nginxdemos/hello:0.4
    ports:
      - "80:80"

  app-a:
    build: ../../app/fastapi/
    image: ghcr.io/blueswen/grafana-zero-to-hero/fastapi:latest
    ports:
      - "8000:8000"

  app-b:
    build: ../../app/fastapi/
    image: ghcr.io/blueswen/grafana-zero-to-hero/fastapi:latest
    ports:
      - "8001:8000"

  app-c:
    build: ../../app/fastapi/
    image: ghcr.io/blueswen/grafana-zero-to-hero/fastapi:latest
    ports:
      - "8002:8000"

  k6:
    image: grafana/k6:1.0.0
    volumes:
      - ./etc/k6-script.js:/k6/script.js
    command: run --vus 3 --duration 6000s /k6/script.js
    environment:
      - MODE=compose
    depends_on:
      - app-a
      - app-b
      - app-c

volumes:
  grafana-data:
