{
 "title": "Gatus",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "name",
    "label": "Name",
    "query": {
     "query": "label_values(gatus_results_total,name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Health Status",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "gatus_results_total{}", "legendFormat": "__auto" }
   ]
  },
  { "title": "$name details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }, "repeat": "name" },
  {
   "title": "Uptime 7d",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gatus_results_total{name=\"$name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime 24h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gatus_results_total{name=\"$name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime 1h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gatus_results_total{name=\"$name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Time 7d",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(gatus_results_duration_seconds{name=\"$name\"}[7d])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Time 24h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(gatus_results_duration_seconds{name=\"$name\"}[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Time 1h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(gatus_results_duration_seconds{name=\"$name\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "gatus_results_duration_seconds{name=\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}