apiVersion: 1
groups:
    - orgId: 1
      name: 1m
      folder: Provision Dashboards
      interval: 1m
      rules:
        - uid: bdznvz4tes2yof
          title: Memory Usage
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 21600
                to: 0
              datasourceUid: prometheus
              model:
                datasource:
                    type: prometheus
                    uid: prometheus
                expr: sum(container_memory_rss{instance=~".*",name=~".+"}) by (name)
                interval: ""
                intervalMs: 15000
                legendFormat: '{{name}}'
                maxDataPoints: 43200
                refId: A
            - refId: B
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 5e+07
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: pMEd7m0Mz
          panelId: 9
          noDataState: NoData
          execErrState: Error
          for: 3m
          annotations:
            __dashboardUid__: pMEd7m0Mz
            __panelId__: "9"
            description: ""
            runbook_url: ""
            summary: ""
          labels:
            "": ""
          isPaused: false
          notification_settings:
            receiver: grafana-default-email
