name: Build and Push Docker Images

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'app/fastapi/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push FastAPI image
        uses: docker/build-push-action@v6
        with:
          context: ./app/fastapi
          push: true
          tags: ghcr.io/${{ github.repository }}/fastapi:latest
          platforms: linux/amd64,linux/arm64
